export const fakeData = [
    {
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Abvelitvitaeeius ",
        content: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet autem numquam odio quae modi recusandae error ex vero. Pariatur, assumenda beatae hic nihil itaque quae quisquam, nesciunt labore adipisci illo officia autem sunt incidunt. Voluptates quasi perspiciatis animi tempora repellendus sequi illum placeat rem aspernatur praesentium adipisci nam totam dignissimos, debitis voluptatibus ullam necessitatibus ab earum corrupti. Animi saepe ad, libero temporibus, nemo voluptate omnis repellat eum quibusdam voluptas eaque aperiam harum fuga alias fugiat voluptates officia maiores magni, iusto nisi. Culpa veniam fuga vel totam distinctio libero unde porro, sit quasi blanditiis excepturi voluptate nobis facilis quibusdam tenetur earum cupiditate ducimus neque. Aliquam id dolor atque numquam alias voluptate consequuntur, pariatur reprehenderit distinctio similique quia deserunt non molestiae accusantium quibusdam unde nobis minus veritatis ipsam nemo, sint sunt. Quas, delectus quia at, nostrum sint mollitia fuga quos ducimus aut corrupti harum. Quibusdam, deleniti ipsum corporis totam reiciendis dolore consequuntur dignissimos veniam optio quidem atque nulla. Nemo repudiandae voluptatum necessitatibus molestias quaerat architecto laboriosam temporibus nihil autem, libero veniam ab quibusdam dicta quia perferendis eligendi beatae, illo a odit optio quas ex voluptates voluptatibus deserunt. Quaerat qui ducimus hic sapiente ea nobis ipsa magnam soluta at quia temporibus, earum maxime eveniet voluptatum cumque, autem quae nemo cupiditate, commodi eligendi adipisci fuga rem accusantium. Accusamus, doloribus molestias assumenda non nihil officiis odio ex quibusdam, provident obcaecati aspernatur fuga recusandae! Natus, odio quia at unde soluta voluptatum nostrum! Nam aspernatur vel provident perspiciatis incidunt, debitis a, beatae officiis iure, voluptas deleniti minus hic. Voluptatibus natus voluptatem id provident alias possimus veritatis quas ad temporibus nesciunt culpa, quis, explicabo dolorum perspiciatis modi ducimus saepe, illo dignissimos. Veritatis quis ratione voluptates debitis consequatur! Est velit quasi repudiandae a dignissimos ab quibusdam labore voluptatum expedita ducimus excepturi facilis eos porro, maxime eius neque quidem rem!",
        author: "Imam Dahir Dan-Azumi",
        publishDate: "12/10/2022",
    },
    {
        title: "The World Bank assisted programme boosting technology in africa",
        content: "autem numquam odio quae modi recusandae error ex vero. Pariatur, assumenda beatae hic nihil itaque quae quisquam, nesciunt labore adipisci illo officia autem sunt incidunt. Voluptates quasi perspiciatis animi tempora repellendus sequi illum placeat rem aspernatur praesentium adipisci nam totam dignissimos, debitis voluptatibus ullam necessitatibus ab earum corrupti. Animi saepe ad, libero temporibus, nemo voluptate omnis repellat eum quibusdam voluptas eaque aperiam harum fuga alias fugiat voluptates officia maiores magni, iusto nisi. Culpa veniam fuga vel totam distinctio libero unde porro, sit quasi blanditiis excepturi voluptate nobis facilis quibusdam tenetur earum cupiditate ducimus neque. Aliquam id dolor atque numquam alias voluptate consequuntur, pariatur reprehenderit distinctio similique quia deserunt non molestiae accusantium quibusdam unde nobis minus veritatis ipsam nemo, sint sunt. Quas, delectus quia at, nostrum sint mollitia fuga quos ducimus aut corrupti harum. Quibusdam, deleniti ipsum corporis totam reiciendis dolore consequuntur dignissimos veniam optio quidem atque nulla. Nemo repudiandae voluptatum necessitatibus molestias quaerat architecto laboriosam temporibus nihil autem, libero veniam ab quibusdam dicta quia perferendis eligendi beatae, illo a odit optio quas ex voluptates voluptatibus deserunt. Quaerat qui ducimus hic sapiente ea nobis ipsa magnam soluta at quia temporibus, earum maxime eveniet voluptatum cumque, autem quae nemo cupiditate, commodi eligendi adipisci fuga rem accusantium. Accusamus, doloribus molestias assumenda non nihil officiis odio ex quibusdam, provident obcaecati aspernatur fuga recusandae! Natus, odio quia at unde soluta voluptatum nostrum! Nam aspernatur vel provident perspiciatis incidunt, debitis a, beatae officiis iure, voluptas deleniti minus hic. Voluptatibus natus voluptatem id provident alias possimus veritatis quas ad temporibus nesciunt culpa, quis, explicabo dolorum perspiciatis modi ducimus saepe, illo dignissimos. Veritatis quis ratione voluptates debitis consequatur! Est velit quasi repudiandae a dignissimos ab quibusdam labore voluptatum expedita ducimus excepturi facilis eos porro, maxime eius neque quidem rem!",
        author: "Adams Levine",
        publishDate: "22/11/2022"
    },
    {
        title: "Cryptocurrency market sees a bloodbath this week",
        content: "Amet autem numquam odio quae modi recusandae error ex vero. Pariatur, assumenda beatae hic nihil itaque quae quisquam, nesciunt labore adipisci illo officia autem sunt incidunt. Voluptates quasi perspiciatis animi tempora repellendus sequi illum placeat rem aspernatur praesentium adipisci nam totam dignissimos, debitis voluptatibus ullam necessitatibus ab earum corrupti. Animi saepe ad, libero temporibus, nemo voluptate omnis repellat eum quibusdam voluptas eaque aperiam harum fuga alias fugiat voluptates officia maiores magni, iusto nisi. Culpa veniam fuga vel totam distinctio libero unde porro, sit quasi blanditiis excepturi voluptate nobis facilis quibusdam tenetur earum cupiditate ducimus neque. Aliquam id dolor atque numquam alias voluptate consequuntur, pariatur reprehenderit distinctio similique quia deserunt non molestiae accusantium quibusdam unde nobis minus veritatis ipsam nemo, sint sunt. Quas, delectus quia at, nostrum sint mollitia fuga quos ducimus aut corrupti harum. Quibusdam, deleniti ipsum corporis totam reiciendis dolore consequuntur dignissimos veniam optio quidem atque nulla. Nemo repudiandae voluptatum necessitatibus molestias quaerat architecto laboriosam temporibus nihil autem, libero veniam ab quibusdam dicta quia perferendis eligendi beatae, illo a odit optio quas ex voluptates voluptatibus deserunt. Quaerat qui ducimus hic sapiente ea nobis ipsa magnam soluta at quia temporibus, earum maxime eveniet voluptatum cumque, autem quae nemo cupiditate, commodi eligendi adipisci fuga rem accusantium. Accusamus, doloribus molestias assumenda non nihil officiis odio ex quibusdam, provident obcaecati aspernatur fuga recusandae! Natus, odio quia at unde soluta voluptatum nostrum! Nam aspernatur vel provident perspiciatis incidunt, debitis a, beatae officiis iure, voluptas deleniti minus hic. Voluptatibus natus voluptatem id provident alias possimus veritatis quas ad temporibus nesciunt culpa, quis, explicabo dolorum perspiciatis modi ducimus saepe, illo dignissimos. Veritatis quis ratione voluptates debitis consequatur! Est velit quasi repudiandae a dignissimos ab quibusdam labore voluptatum expedita ducimus excepturi facilis eos porro, maxime eius neque quidem rem!",
        author: "Megan Darasiki",
        publishDate: "2/11/2022"
    },
    {
        title: "Startups Funding in africa getting tougher as more failures reported",
        content: "recusandae error ex vero. Pariatur, assumenda beatae hic nihil itaque quae quisquam, nesciunt labore adipisci illo officia autem sunt incidunt. Voluptates quasi perspiciatis animi tempora repellendus sequi illum placeat rem aspernatur praesentium adipisci nam totam dignissimos, debitis voluptatibus ullam necessitatibus ab earum corrupti. Animi saepe ad, libero temporibus, nemo voluptate omnis repellat eum quibusdam voluptas eaque aperiam harum fuga alias fugiat voluptates officia maiores magni, iusto nisi. Culpa veniam fuga vel totam distinctio libero unde porro, sit quasi blanditiis excepturi voluptate nobis facilis quibusdam tenetur earum cupiditate ducimus neque. Aliquam id dolor atque numquam alias voluptate consequuntur, pariatur reprehenderit distinctio similique quia deserunt non molestiae accusantium quibusdam unde nobis minus veritatis ipsam nemo, sint sunt. Quas, delectus quia at, nostrum sint mollitia fuga quos ducimus aut corrupti harum. Quibusdam, deleniti ipsum corporis totam reiciendis dolore consequuntur dignissimos veniam optio quidem atque nulla. Nemo repudiandae voluptatum necessitatibus molestias quaerat architecto laboriosam temporibus nihil autem, libero veniam ab quibusdam dicta quia perferendis eligendi beatae, illo a odit optio quas ex voluptates voluptatibus deserunt. Quaerat qui ducimus hic sapiente ea nobis ipsa magnam soluta at quia temporibus, earum maxime eveniet voluptatum cumque, autem quae nemo cupiditate, commodi eligendi adipisci fuga rem accusantium. Accusamus, doloribus molestias assumenda non nihil officiis odio ex quibusdam, provident obcaecati aspernatur fuga recusandae! Natus, odio quia at unde soluta voluptatum nostrum! Nam aspernatur vel provident perspiciatis incidunt, debitis a, beatae officiis iure, voluptas deleniti minus hic. Voluptatibus natus voluptatem id provident alias possimus veritatis quas ad temporibus nesciunt culpa, quis, explicabo dolorum perspiciatis modi ducimus saepe, illo dignissimos. Veritatis quis ratione voluptates debitis consequatur! Est velit quasi repudiandae a dignissimos ab quibusdam labore voluptatum expedita ducimus excepturi facilis eos porro, maxime eius neque quidem rem!",
        author: "John Doe",
        publishDate: "24/11/2022"
    },
]